### ISSUE TITLE
Failed to transform Event without Metadata

### ISSUE THREAD

**Issue by AdrianM** [EventStore/replicator#39]
When i try to replicate an Event which has no Metadata object, the replicator fails with the given error:

`{"@t":"2022-02-25T13:44:18.1878515Z","@m":"Error occured in the \"PrepareContext\" pipe: \"One or more errors occurred. (Line 1: Unexpected end of input)\"","@i":"c9acd0a5","@l":"Error","@x":"System.AggregateException: One or more errors occurred. (Line 1: Unexpected end of input) ---> Esprima.ParserException: Line 1: Unexpected end of input
   at Jint.Native.Json.JsonParser.ThrowError(Token token, String messageFormat, Object[] arguments)
      at Jint.Native.Json.JsonParser.ThrowUnexpected(Token token)
         at Jint.Native.Json.JsonParser.ParseJsonValue()
            at Jint.Native.Json.JsonParser.Parse(String code, ParserOptions options)
               at EventStore.Replicator.JavaScript.JsTransform.Transform(OriginalEvent original, CancellationToken cancellationToken) in /app/src/EventStore.Replicator.JavaScript/JsTransform.cs:line 96
                  at EventStore.Replicator.Prepare.TransformFilter.<>c__DisplayClass2_0.<<Send>g__Transform|2>d.MoveNext() in /app/src/EventStore.Replicator/Prepare/TransformFilter.cs:line 41
                     --- End of inner exception stack trace ---
                        at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
                           at Ubiquitous.Metrics.Metrics.Measure[T](Func1 action, IHistogramMetric metric, ICountMetric errorCount, String[] labels, Int32 count)
                              at EventStore.Replicator.Prepare.TransformFilter.Send(PrepareContext context, IPipe1 next) in /app/src/EventStore.Replicator/Prepare/TransformFilter.cs:line 42
                                 at EventStore.Replicator.Prepare.EventFilterFilter.Send(PrepareContext context, IPipe1 next) in /app/src/EventStore.Replicator/Prepare/EventFilterFilter.cs:line 25
                                    at GreenPipes.Filters.ConcurrencyLimitFilter1.Send(TContext context, IPipe1 next)
                                       at EventStore.Replicator.LoggingFilter1.Send(T context, IPipe1 next) in /app/src/EventStore.Replicator/Logging.cs:line 19","Type":"PrepareContext","Message":"One or more errors occurred. (Line 1: Unexpected end of input)","SourceContext":"EventStore.Replicator.LoggingFilter1[T]"}
`

This could be a bug in the File "JsTransform.cs", where the line 83 is currently...
`parser.Parse(original.Metadata?.AsUtf8String())`

...but it should be something like:
`original.Metadata ? parser.Parse(original.Metadata.AsUtf8String()) : null`

The ?-operator is there, but still the parse method is called with an empty input (the bug was probably introduced with the commit https://github.com/EventStore/replicator/commit/0c0d917e75e4fa8fc09c34c0a2dac27fb3d79b40#diff-a63904b6f59152bb85dfd9e86b2c2f8f37c9f00a968eae983c6fcc87ad39cef2).

Unfortunately, i do not have a local .NET setup at the moment and therefore can not validate the problem and create a PullRequest. I am not sure if this is actually the solution, but I would be thankful if you could validate and release this proposal.

(Setup: Replicator 0.4.0, EventStore 20.10, on Kubernetes with HELM)

Thank you and best regards, 
Adrian

**Comment by alexeyzimarev** [comment]
It's because I am planning to move to Docker Hub instead of GCR, but it's still WIP.

**Comment by AdrianM** [comment]
Thanks for the info. Is there already a rough estimation about when we could use 0.4.2 with HELM? (either via Docker Hub or temporary via GCR?). It would be helpful since we are currently using the replicator for the migration to the new EventStore 21.10 in our project.

**Comment by alexeyzimarev** [comment]
It's on Docker Hub now and I updated the chart as well

**Comment by AdrianM** [comment]
Perfect, thanks!
